In [74]:
import numpy as np

In [75]:
def extendmatrix(matrix):
    matrix_ampli = np.array([  [matrix[0,0],matrix[0,1],matrix[0,2]],
        [matrix[1,0],matrix[1,1],matrix[1,2]], [matrix[2,0],matrix[2,1],matrix[2,2] ],  
        [matrix[0,0],matrix[0,1],matrix[0,2]],  [matrix[1,0],matrix[1,1],matrix[1,2]]    ])
    return matrix_ampli

def multi(matrix):
    print(f'[ ({matrix[0,0]}*{matrix[1,1]}*{matrix[2,2]})+({matrix[1,0]}*{matrix[2,1]}*{matrix[3,2]})+({matrix[2,0]}*{matrix[3,1]}*{matrix[4,2]}) ] - [ ({matrix[0,2]}*{matrix[1,1]}*{matrix[2,0]})+({matrix[1,2]}*{matrix[2,1]}*{matrix[3,0]})+({matrix[2,2]}*{matrix[3,1]}*{matrix[4,0]}) ]') 
    print(f'[ ({matrix[0,0]*matrix[1,1]*matrix[2,2]})+({matrix[1,0]*matrix[2,1]*matrix[3,2]})+({matrix[2,0]*matrix[3,1]*matrix[4,2]}) ] - [ ({matrix[0,2]*matrix[1,1]*matrix[2,0]})+({matrix[1,2]*matrix[2,1]*matrix[3,0]})+({matrix[2,2]*matrix[3,1]*matrix[4,0]}) ]') 
    print(f' {(matrix[0,0]*matrix[1,1]*matrix[2,2])+(matrix[1,0]*matrix[2,1]*matrix[3,2])+(matrix[2,0]*matrix[3,1]*matrix[4,2])}  -  {(matrix[0,2]*matrix[1,1]*matrix[2,0])+(matrix[1,2]*matrix[2,1]*matrix[3,0])+(matrix[2,2]*matrix[3,1]*matrix[4,0])} ') 
    print(f' {(((matrix[0,0]*matrix[1,1]*matrix[2,2])+(matrix[1,0]*matrix[2,1]*matrix[3,2])+(matrix[2,0]*matrix[3,1]*matrix[4,2]))  -  ((matrix[0,2]*matrix[1,1]*matrix[2,0])+(matrix[1,2]*matrix[2,1]*matrix[3,0])+(matrix[2,2]*matrix[3,1]*matrix[4,0])))} ') 
    res = (((matrix[0,0]*matrix[1,1]*matrix[2,2])+(matrix[1,0]*matrix[2,1]*matrix[3,2])+(matrix[2,0]*matrix[3,1]*matrix[4,2]))  -  ((matrix[0,2]*matrix[1,1]*matrix[2,0])+(matrix[1,2]*matrix[2,1]*matrix[3,0])+(matrix[2,2]*matrix[3,1]*matrix[4,0]))) 
    return res


In [76]:
print("Sarrus Rule, determinat")


#matrix = np.array([ [3,2,1,2], [-2,1,-7,0], [3,-1,8,2]  ])
# REPLACE MATRIX HERE!
matrix = np.array([ [2,1,-1,1], [1,-2,2,3], [3,-2,1,2]  ])

matrix_coe = np.array([  [matrix[0,0],matrix[0,1],matrix[0,2]],
    [matrix[1,0],matrix[1,1],matrix[1,2]], [matrix[2,0],matrix[2,1],matrix[2,2]    ] ])

print('Matrix')
print(matrix)
print('-------------------------')
print('Coefiient matrix')
print(matrix_coe)

Sarrus Rule, determinat
Matrix
[[ 2  1 -1  1]
 [ 1 -2  2  3]
 [ 3 -2  1  2]]
-------------------------
Coefiient matrix
[[ 2  1 -1]
 [ 1 -2  2]
 [ 3 -2  1]]


In [77]:
matrix_coe_ampli = extendmatrix(matrix_coe)

print('-------------------------')
print('Extended matrix')
print(f'{matrix_coe_ampli}')
print()
d = multi(matrix_coe_ampli)

-------------------------
Extended matrix
[[ 2  1 -1]
 [ 1 -2  2]
 [ 3 -2  1]
 [ 2  1 -1]
 [ 1 -2  2]]

[ (2*-2*1)+(1*-2*-1)+(3*1*2) ] - [ (-1*-2*3)+(2*-2*2)+(1*1*1) ]
[ (-4)+(2)+(6) ] - [ (6)+(-8)+(1) ]
 4  -  -1 
 5 


In [78]:

# D_x
print('')
matrix_dx = np.array([  [matrix[0,3],matrix[0,1],matrix[0,2]],
    [matrix[1,3],matrix[1,1],matrix[1,2]], [matrix[2,3],matrix[2,1],matrix[2,2]  ] ])

print('Matrix Dx')
print(matrix_dx)

matrix_dx_ampli = extendmatrix(matrix_dx)

print('-------------------------')
print('Matrix Dx extend')
print(matrix_dx_ampli)
print()
dx = multi(matrix_dx_ampli)
print()
print(f'Dx/D={dx}/{d}={dx/d}')


Matrix Dx
[[ 1  1 -1]
 [ 3 -2  2]
 [ 2 -2  1]]
-------------------------
Matrix Dx extend
[[ 1  1 -1]
 [ 3 -2  2]
 [ 2 -2  1]
 [ 1  1 -1]
 [ 3 -2  2]]

[ (1*-2*1)+(3*-2*-1)+(2*1*2) ] - [ (-1*-2*2)+(2*-2*1)+(1*1*3) ]
[ (-2)+(6)+(4) ] - [ (4)+(-4)+(3) ]
 8  -  3 
 5 

Dx/D=5/5=1.0


In [79]:
# D_y
print('')
matrix_dy = np.array([  [matrix[0,0],matrix[0,3],matrix[0,2]],
    [matrix[1,0],matrix[1,3],matrix[1,2]], [matrix[2,0],matrix[2,3],matrix[2,2]  ] ])

print('Matrix Dy')
print(matrix_dy)

matrix_dy_ampli = extendmatrix(matrix_dy)

print('-------------------------')
print('Matrix Dy extend')
print(matrix_dy_ampli)
print()
dy = multi(matrix_dy_ampli)
print()
print(f'Dy/D={dy}/{d}={dy/d}')


Matrix Dy
[[ 2  1 -1]
 [ 1  3  2]
 [ 3  2  1]]
-------------------------
Matrix Dy extend
[[ 2  1 -1]
 [ 1  3  2]
 [ 3  2  1]
 [ 2  1 -1]
 [ 1  3  2]]

[ (2*3*1)+(1*2*-1)+(3*1*2) ] - [ (-1*3*3)+(2*2*2)+(1*1*1) ]
[ (6)+(-2)+(6) ] - [ (-9)+(8)+(1) ]
 10  -  0 
 10 

Dy/D=10/5=2.0


In [80]:

# D_z
print('')
matrix_dz = np.array([  [matrix[0,0],matrix[0,1],matrix[0,3]],
    [matrix[1,0],matrix[1,1],matrix[1,3]], [matrix[2,0],matrix[2,1],matrix[2,3]  ] ])

print('Matrix D_z')
print(matrix_dz)

matrix_dz_ampli = extendmatrix(matrix_dz)

print('-------------------------')
print('Matrix D_z extend')
print(matrix_dz_ampli)
print()
dz = multi(matrix_dz_ampli)
print()
print(f'Dz/D={dz}/{d}={dz/d}')


Matrix D_z
[[ 2  1  1]
 [ 1 -2  3]
 [ 3 -2  2]]
-------------------------
Matrix D_z extend
[[ 2  1  1]
 [ 1 -2  3]
 [ 3 -2  2]
 [ 2  1  1]
 [ 1 -2  3]]

[ (2*-2*2)+(1*-2*1)+(3*1*3) ] - [ (1*-2*3)+(3*-2*2)+(2*1*1) ]
[ (-8)+(-2)+(9) ] - [ (-6)+(-12)+(2) ]
 -1  -  -16 
 15 

Dz/D=15/5=3.0


In [81]:
print()
print('-------------------------------')
print('RESULTS...')
print(f'x = {dx/d}')
print(f'y = {dy/d}')
print(f'z = {dz/d}')


-------------------------------
RESULTS...
x = 1.0
y = 2.0
z = 3.0
