In [44]:
import numpy as np


In [45]:
#eq = np.array([[2,1,-1,8],[-3,-1,2,-11],[-2,1,2,-3]])
eq = np.array([[1,1,1,200],[16,50,80,7500],[1,-1,-1,0]])
print(eq)

[[   1    1    1  200]
 [  16   50   80 7500]
 [   1   -1   -1    0]]


In [46]:
eq = np.array([   [ eq[0,0],eq[0,1],eq[0,2],eq[0,3] ], 
                  [ eq[1,0]*eq[0,0]-eq[0,0]*eq[1,0], eq[1,0]*eq[0,1]-eq[0,0]*eq[1,1] , eq[1,0]*eq[0,2]-eq[0,0]*eq[1,2] , eq[1,0]*eq[0,3]-eq[0,0]*eq[1,3]  ]  , 
                  [ eq[2,0],eq[2,1],eq[2,2],eq[2,3] ]  ])
print(eq)

[[    1     1     1   200]
 [    0   -34   -64 -4300]
 [    1    -1    -1     0]]


In [47]:
eq = np.array([    [ eq[0,0],eq[0,1],eq[0,2],eq[0,3] ],  
                   [  eq[1,0],eq[1,1],eq[1,2],eq[1,3]  ]  ,  
                   [  eq[2,0]*eq[0,0]-eq[0,0]*eq[2,0], eq[2,0]*eq[0,1]-eq[0,0]*eq[2,1],  eq[2,0]*eq[0,2]-eq[0,0]*eq[2,2] ,  eq[2,0]*eq[0,3]-eq[0,0]*eq[2,3] ]  ])
print(eq)

[[    1     1     1   200]
 [    0   -34   -64 -4300]
 [    0     2     2   200]]


In [48]:
eq = np.array([   [ eq[0,0],eq[0,1],eq[0,2],eq[0,3] ] ,   
                  [ eq[1,0],eq[1,1],eq[1,2],eq[1,3] ] ,   
                  [ eq[2,0],   eq[2,1]*eq[1,1]-eq[1,1]*eq[2,1],    eq[2,1]*eq[1,2]-eq[1,1]*eq[2,2],     eq[2,1]*eq[1,3]-eq[1,1]*eq[2,3]  ]        ])
print(eq)

[[    1     1     1   200]
 [    0   -34   -64 -4300]
 [    0     0   -60 -1800]]


In [49]:
if eq[2,2] == 0:
    print("Don't have solution")
else:
    z = eq[2,3]/eq[2,2]
    y = (eq[1,3]-eq[1,2]*z)/eq[1,1]
    x = (eq[0,3]-eq[0,2]*z-eq[0,1]*y)/eq[0,0]


In [50]:
print(f'x = {x}')
print(f'y = {y}')
print(f'z = {z}')

x = 100.0
y = 70.0
z = 30.0
